const ERROR_CODE = 400;
const ERROR_NOTFOUND = 404;
const ERROR_DEFAULT = 500;
const ERROR_FORBIDDEN = 403;
const ERROR_AUTH = 401;
const ERROR_CONFLICT = 409;

module.exports = {
  ERROR_CODE,
  ERROR_NOTFOUND,
  ERROR_DEFAULT,
  ERROR_FORBIDDEN,
  ERROR_AUTH,
  ERROR_CONFLICT,
};
